python run_satellites.py --night 180
python run_satellites.py --night 181
python run_satellites.py --night 182
python run_satellites.py --night 183
python run_satellites.py --night 184
python run_satellites.py --night 185
python run_satellites.py --night 186
python run_satellites.py --night 187
python run_satellites.py --night 188
python run_satellites.py --night 189
python run_satellites.py --night 190
python run_satellites.py --night 191
python run_satellites.py --night 192
python run_satellites.py --night 193
python run_satellites.py --night 194
python run_satellites.py --night 195
python run_satellites.py --night 196
python run_satellites.py --night 197
python run_satellites.py --night 198
python run_satellites.py --night 199
python run_satellites.py --night 200
python run_satellites.py --night 201
python run_satellites.py --night 202
python run_satellites.py --night 203
python run_satellites.py --night 204
python run_satellites.py --night 205
python run_satellites.py --night 206
python run_satellites.py --night 207
python run_satellites.py --night 208
python run_satellites.py --night 209
python run_satellites.py --night 210
python run_satellites.py --night 211
python run_satellites.py --night 212
python run_satellites.py --night 213
python run_satellites.py --night 214
python run_satellites.py --night 215
python run_satellites.py --night 216
python run_satellites.py --night 217
python run_satellites.py --night 218
python run_satellites.py --night 219
python run_satellites.py --night 220
python run_satellites.py --night 221
python run_satellites.py --night 222
python run_satellites.py --night 223
python run_satellites.py --night 224
python run_satellites.py --night 225
python run_satellites.py --night 226
python run_satellites.py --night 227
python run_satellites.py --night 228
python run_satellites.py --night 229
python run_satellites.py --night 230
python run_satellites.py --night 231
python run_satellites.py --night 232
python run_satellites.py --night 233
python run_satellites.py --night 234
python run_satellites.py --night 235
python run_satellites.py --night 236
python run_satellites.py --night 237
python run_satellites.py --night 238
python run_satellites.py --night 239
python run_satellites.py --night 240
python run_satellites.py --night 241
python run_satellites.py --night 242
python run_satellites.py --night 243
python run_satellites.py --night 244
python run_satellites.py --night 245
python run_satellites.py --night 246
python run_satellites.py --night 247
python run_satellites.py --night 248
python run_satellites.py --night 249
python run_satellites.py --night 250
python run_satellites.py --night 251
python run_satellites.py --night 252
python run_satellites.py --night 253
python run_satellites.py --night 254
python run_satellites.py --night 255
python run_satellites.py --night 256
python run_satellites.py --night 257
python run_satellites.py --night 258
python run_satellites.py --night 259
python run_satellites.py --night 260
python run_satellites.py --night 261
python run_satellites.py --night 262
python run_satellites.py --night 263
python run_satellites.py --night 264
python run_satellites.py --night 265
python run_satellites.py --night 266
python run_satellites.py --night 267
python run_satellites.py --night 268
python run_satellites.py --night 269
python run_satellites.py --night 270
python run_satellites.py --night 271
python run_satellites.py --night 272
python run_satellites.py --night 273
python run_satellites.py --night 274
python run_satellites.py --night 275
python run_satellites.py --night 276
python run_satellites.py --night 277
python run_satellites.py --night 278
python run_satellites.py --night 279
python run_satellites.py --night 280
python run_satellites.py --night 281
python run_satellites.py --night 282
python run_satellites.py --night 283
python run_satellites.py --night 284
python run_satellites.py --night 285
python run_satellites.py --night 286
python run_satellites.py --night 287
python run_satellites.py --night 288
python run_satellites.py --night 289
python run_satellites.py --night 290
python run_satellites.py --night 291
python run_satellites.py --night 292
python run_satellites.py --night 293
python run_satellites.py --night 294
python run_satellites.py --night 295
python run_satellites.py --night 296
python run_satellites.py --night 297
python run_satellites.py --night 298
python run_satellites.py --night 299
python run_satellites.py --night 300
python run_satellites.py --night 301
python run_satellites.py --night 302
python run_satellites.py --night 303
python run_satellites.py --night 304
python run_satellites.py --night 305
python run_satellites.py --night 306
python run_satellites.py --night 307
python run_satellites.py --night 308
python run_satellites.py --night 309
python run_satellites.py --night 310
python run_satellites.py --night 311
python run_satellites.py --night 312
python run_satellites.py --night 313
python run_satellites.py --night 314
python run_satellites.py --night 315
python run_satellites.py --night 316
python run_satellites.py --night 317
python run_satellites.py --night 318
python run_satellites.py --night 319
python run_satellites.py --night 320
python run_satellites.py --night 321
python run_satellites.py --night 322
python run_satellites.py --night 323
python run_satellites.py --night 324
python run_satellites.py --night 325
python run_satellites.py --night 326
python run_satellites.py --night 327
python run_satellites.py --night 328
python run_satellites.py --night 329
python run_satellites.py --night 330
python run_satellites.py --night 331
python run_satellites.py --night 332
python run_satellites.py --night 333
python run_satellites.py --night 334
python run_satellites.py --night 335
python run_satellites.py --night 336
python run_satellites.py --night 337
python run_satellites.py --night 338
python run_satellites.py --night 339
python run_satellites.py --night 340
python run_satellites.py --night 341
python run_satellites.py --night 342
python run_satellites.py --night 343
python run_satellites.py --night 344
python run_satellites.py --night 345
python run_satellites.py --night 346
python run_satellites.py --night 347
python run_satellites.py --night 348
python run_satellites.py --night 349
python run_satellites.py --night 350
python run_satellites.py --night 351
python run_satellites.py --night 352
python run_satellites.py --night 353
python run_satellites.py --night 354
python run_satellites.py --night 355
python run_satellites.py --night 356
python run_satellites.py --night 357
python run_satellites.py --night 358
python run_satellites.py --night 359
python run_satellites.py --night 360
python run_satellites.py --night 361
python run_satellites.py --night 362
python run_satellites.py --night 363
python run_satellites.py --night 364
