python run_satellites.py --night 0
python run_satellites.py --night 1
python run_satellites.py --night 2
python run_satellites.py --night 3
python run_satellites.py --night 4
python run_satellites.py --night 5
python run_satellites.py --night 6
python run_satellites.py --night 7
python run_satellites.py --night 8
python run_satellites.py --night 9
python run_satellites.py --night 10
python run_satellites.py --night 11
python run_satellites.py --night 12
python run_satellites.py --night 13
python run_satellites.py --night 14
python run_satellites.py --night 15
python run_satellites.py --night 16
python run_satellites.py --night 17
python run_satellites.py --night 18
python run_satellites.py --night 19
python run_satellites.py --night 20
python run_satellites.py --night 21
python run_satellites.py --night 22
python run_satellites.py --night 23
python run_satellites.py --night 24
python run_satellites.py --night 25
python run_satellites.py --night 26
python run_satellites.py --night 27
python run_satellites.py --night 28
python run_satellites.py --night 29
python run_satellites.py --night 30
python run_satellites.py --night 31
python run_satellites.py --night 32
python run_satellites.py --night 33
python run_satellites.py --night 34
python run_satellites.py --night 35
python run_satellites.py --night 36
python run_satellites.py --night 37
python run_satellites.py --night 38
python run_satellites.py --night 39
python run_satellites.py --night 40
python run_satellites.py --night 41
python run_satellites.py --night 42
python run_satellites.py --night 43
python run_satellites.py --night 44
python run_satellites.py --night 45
python run_satellites.py --night 46
python run_satellites.py --night 47
python run_satellites.py --night 48
python run_satellites.py --night 49
python run_satellites.py --night 50
python run_satellites.py --night 51
python run_satellites.py --night 52
python run_satellites.py --night 53
python run_satellites.py --night 54
python run_satellites.py --night 55
python run_satellites.py --night 56
python run_satellites.py --night 57
python run_satellites.py --night 58
python run_satellites.py --night 59
python run_satellites.py --night 60
python run_satellites.py --night 61
python run_satellites.py --night 62
python run_satellites.py --night 63
python run_satellites.py --night 64
python run_satellites.py --night 65
python run_satellites.py --night 66
python run_satellites.py --night 67
python run_satellites.py --night 68
python run_satellites.py --night 69
python run_satellites.py --night 70
python run_satellites.py --night 71
python run_satellites.py --night 72
python run_satellites.py --night 73
python run_satellites.py --night 74
python run_satellites.py --night 75
python run_satellites.py --night 76
python run_satellites.py --night 77
python run_satellites.py --night 78
python run_satellites.py --night 79
python run_satellites.py --night 80
python run_satellites.py --night 81
python run_satellites.py --night 82
python run_satellites.py --night 83
python run_satellites.py --night 84
python run_satellites.py --night 85
python run_satellites.py --night 86
python run_satellites.py --night 87
python run_satellites.py --night 88
python run_satellites.py --night 89
python run_satellites.py --night 90
python run_satellites.py --night 91
python run_satellites.py --night 92
python run_satellites.py --night 93
python run_satellites.py --night 94
python run_satellites.py --night 95
python run_satellites.py --night 96
python run_satellites.py --night 97
python run_satellites.py --night 98
python run_satellites.py --night 99
python run_satellites.py --night 100
python run_satellites.py --night 101
python run_satellites.py --night 102
python run_satellites.py --night 103
python run_satellites.py --night 104
python run_satellites.py --night 105
python run_satellites.py --night 106
python run_satellites.py --night 107
python run_satellites.py --night 108
python run_satellites.py --night 109
python run_satellites.py --night 110
python run_satellites.py --night 111
python run_satellites.py --night 112
python run_satellites.py --night 113
python run_satellites.py --night 114
python run_satellites.py --night 115
python run_satellites.py --night 116
python run_satellites.py --night 117
python run_satellites.py --night 118
python run_satellites.py --night 119
python run_satellites.py --night 120
python run_satellites.py --night 121
python run_satellites.py --night 122
python run_satellites.py --night 123
python run_satellites.py --night 124
python run_satellites.py --night 125
python run_satellites.py --night 126
python run_satellites.py --night 127
python run_satellites.py --night 128
python run_satellites.py --night 129
python run_satellites.py --night 130
python run_satellites.py --night 131
python run_satellites.py --night 132
python run_satellites.py --night 133
python run_satellites.py --night 134
python run_satellites.py --night 135
python run_satellites.py --night 136
python run_satellites.py --night 137
python run_satellites.py --night 138
python run_satellites.py --night 139
python run_satellites.py --night 140
python run_satellites.py --night 141
python run_satellites.py --night 142
python run_satellites.py --night 143
python run_satellites.py --night 144
python run_satellites.py --night 145
python run_satellites.py --night 146
python run_satellites.py --night 147
python run_satellites.py --night 148
python run_satellites.py --night 149
python run_satellites.py --night 150
python run_satellites.py --night 151
python run_satellites.py --night 152
python run_satellites.py --night 153
python run_satellites.py --night 154
python run_satellites.py --night 155
python run_satellites.py --night 156
python run_satellites.py --night 157
python run_satellites.py --night 158
python run_satellites.py --night 159
python run_satellites.py --night 160
python run_satellites.py --night 161
python run_satellites.py --night 162
python run_satellites.py --night 163
python run_satellites.py --night 164
python run_satellites.py --night 165
python run_satellites.py --night 166
python run_satellites.py --night 167
python run_satellites.py --night 168
python run_satellites.py --night 169
python run_satellites.py --night 170
python run_satellites.py --night 171
python run_satellites.py --night 172
python run_satellites.py --night 173
python run_satellites.py --night 174
python run_satellites.py --night 175
python run_satellites.py --night 176
python run_satellites.py --night 177
python run_satellites.py --night 178
python run_satellites.py --night 179
python run_satellites.py --night 180
python run_satellites.py --night 181
python run_satellites.py --night 182
python run_satellites.py --night 183
python run_satellites.py --night 184
python run_satellites.py --night 185
python run_satellites.py --night 186
python run_satellites.py --night 187
python run_satellites.py --night 188
python run_satellites.py --night 189
python run_satellites.py --night 190
python run_satellites.py --night 191
python run_satellites.py --night 192
python run_satellites.py --night 193
python run_satellites.py --night 194
python run_satellites.py --night 195
python run_satellites.py --night 196
python run_satellites.py --night 197
python run_satellites.py --night 198
python run_satellites.py --night 199
python run_satellites.py --night 200
python run_satellites.py --night 201
python run_satellites.py --night 202
python run_satellites.py --night 203
python run_satellites.py --night 204
python run_satellites.py --night 205
python run_satellites.py --night 206
python run_satellites.py --night 207
python run_satellites.py --night 208
python run_satellites.py --night 209
python run_satellites.py --night 210
python run_satellites.py --night 211
python run_satellites.py --night 212
python run_satellites.py --night 213
python run_satellites.py --night 214
python run_satellites.py --night 215
python run_satellites.py --night 216
python run_satellites.py --night 217
python run_satellites.py --night 218
python run_satellites.py --night 219
python run_satellites.py --night 220
python run_satellites.py --night 221
python run_satellites.py --night 222
python run_satellites.py --night 223
python run_satellites.py --night 224
python run_satellites.py --night 225
python run_satellites.py --night 226
python run_satellites.py --night 227
python run_satellites.py --night 228
python run_satellites.py --night 229
python run_satellites.py --night 230
python run_satellites.py --night 231
python run_satellites.py --night 232
python run_satellites.py --night 233
python run_satellites.py --night 234
python run_satellites.py --night 235
python run_satellites.py --night 236
python run_satellites.py --night 237
python run_satellites.py --night 238
python run_satellites.py --night 239
python run_satellites.py --night 240
python run_satellites.py --night 241
python run_satellites.py --night 242
python run_satellites.py --night 243
python run_satellites.py --night 244
python run_satellites.py --night 245
python run_satellites.py --night 246
python run_satellites.py --night 247
python run_satellites.py --night 248
python run_satellites.py --night 249
python run_satellites.py --night 250
python run_satellites.py --night 251
python run_satellites.py --night 252
python run_satellites.py --night 253
python run_satellites.py --night 254
python run_satellites.py --night 255
python run_satellites.py --night 256
python run_satellites.py --night 257
python run_satellites.py --night 258
python run_satellites.py --night 259
python run_satellites.py --night 260
python run_satellites.py --night 261
python run_satellites.py --night 262
python run_satellites.py --night 263
python run_satellites.py --night 264
python run_satellites.py --night 265
python run_satellites.py --night 266
python run_satellites.py --night 267
python run_satellites.py --night 268
python run_satellites.py --night 269
python run_satellites.py --night 270
python run_satellites.py --night 271
python run_satellites.py --night 272
python run_satellites.py --night 273
python run_satellites.py --night 274
python run_satellites.py --night 275
python run_satellites.py --night 276
python run_satellites.py --night 277
python run_satellites.py --night 278
python run_satellites.py --night 279
python run_satellites.py --night 280
python run_satellites.py --night 281
python run_satellites.py --night 282
python run_satellites.py --night 283
python run_satellites.py --night 284
python run_satellites.py --night 285
python run_satellites.py --night 286
python run_satellites.py --night 287
python run_satellites.py --night 288
python run_satellites.py --night 289
python run_satellites.py --night 290
python run_satellites.py --night 291
python run_satellites.py --night 292
python run_satellites.py --night 293
python run_satellites.py --night 294
python run_satellites.py --night 295
python run_satellites.py --night 296
python run_satellites.py --night 297
python run_satellites.py --night 298
python run_satellites.py --night 299
python run_satellites.py --night 300
python run_satellites.py --night 301
python run_satellites.py --night 302
python run_satellites.py --night 303
python run_satellites.py --night 304
python run_satellites.py --night 305
python run_satellites.py --night 306
python run_satellites.py --night 307
python run_satellites.py --night 308
python run_satellites.py --night 309
python run_satellites.py --night 310
python run_satellites.py --night 311
python run_satellites.py --night 312
python run_satellites.py --night 313
python run_satellites.py --night 314
python run_satellites.py --night 315
python run_satellites.py --night 316
python run_satellites.py --night 317
python run_satellites.py --night 318
python run_satellites.py --night 319
python run_satellites.py --night 320
python run_satellites.py --night 321
python run_satellites.py --night 322
python run_satellites.py --night 323
python run_satellites.py --night 324
python run_satellites.py --night 325
python run_satellites.py --night 326
python run_satellites.py --night 327
python run_satellites.py --night 328
python run_satellites.py --night 329
python run_satellites.py --night 330
python run_satellites.py --night 331
python run_satellites.py --night 332
python run_satellites.py --night 333
python run_satellites.py --night 334
python run_satellites.py --night 335
python run_satellites.py --night 336
python run_satellites.py --night 337
python run_satellites.py --night 338
python run_satellites.py --night 339
python run_satellites.py --night 340
python run_satellites.py --night 341
python run_satellites.py --night 342
python run_satellites.py --night 343
python run_satellites.py --night 344
python run_satellites.py --night 345
python run_satellites.py --night 346
python run_satellites.py --night 347
python run_satellites.py --night 348
python run_satellites.py --night 349
python run_satellites.py --night 350
python run_satellites.py --night 351
python run_satellites.py --night 352
python run_satellites.py --night 353
python run_satellites.py --night 354
python run_satellites.py --night 355
python run_satellites.py --night 356
python run_satellites.py --night 357
python run_satellites.py --night 358
python run_satellites.py --night 359
python run_satellites.py --night 360
python run_satellites.py --night 361
python run_satellites.py --night 362
python run_satellites.py --night 363
python run_satellites.py --night 364
