python run_satellites.py --night 0
python run_satellites.py --night 1
python run_satellites.py --night 10
python run_satellites.py --night 11
python run_satellites.py --night 12
python run_satellites.py --night 13
python run_satellites.py --night 14
python run_satellites.py --night 18
python run_satellites.py --night 19
python run_satellites.py --night 20
python run_satellites.py --night 22
python run_satellites.py --night 23
python run_satellites.py --night 24
python run_satellites.py --night 26
python run_satellites.py --night 30
python run_satellites.py --night 32
python run_satellites.py --night 35
python run_satellites.py --night 36
python run_satellites.py --night 38
python run_satellites.py --night 40
python run_satellites.py --night 41
python run_satellites.py --night 43
python run_satellites.py --night 44
python run_satellites.py --night 45
python run_satellites.py --night 47
python run_satellites.py --night 48
python run_satellites.py --night 49
python run_satellites.py --night 50
python run_satellites.py --night 51
python run_satellites.py --night 52
python run_satellites.py --night 53
python run_satellites.py --night 59
python run_satellites.py --night 60
python run_satellites.py --night 63
python run_satellites.py --night 64
python run_satellites.py --night 66
python run_satellites.py --night 67
python run_satellites.py --night 68
python run_satellites.py --night 69
python run_satellites.py --night 71
python run_satellites.py --night 72
python run_satellites.py --night 73
python run_satellites.py --night 74
python run_satellites.py --night 82
python run_satellites.py --night 83
python run_satellites.py --night 84
python run_satellites.py --night 86
python run_satellites.py --night 91
python run_satellites.py --night 92
python run_satellites.py --night 95
python run_satellites.py --night 96
python run_satellites.py --night 97
python run_satellites.py --night 98
python run_satellites.py --night 99
python run_satellites.py --night 100
python run_satellites.py --night 101
python run_satellites.py --night 102
python run_satellites.py --night 106
python run_satellites.py --night 109
python run_satellites.py --night 110
python run_satellites.py --night 116
python run_satellites.py --night 118
python run_satellites.py --night 119
python run_satellites.py --night 120
python run_satellites.py --night 121
python run_satellites.py --night 122
python run_satellites.py --night 123
python run_satellites.py --night 124
python run_satellites.py --night 125
python run_satellites.py --night 126
python run_satellites.py --night 129
python run_satellites.py --night 130
python run_satellites.py --night 132
python run_satellites.py --night 133
python run_satellites.py --night 134
python run_satellites.py --night 135
python run_satellites.py --night 136
python run_satellites.py --night 137
python run_satellites.py --night 138
python run_satellites.py --night 140
python run_satellites.py --night 141
python run_satellites.py --night 142
python run_satellites.py --night 144
python run_satellites.py --night 145
python run_satellites.py --night 146
python run_satellites.py --night 147
python run_satellites.py --night 148
python run_satellites.py --night 149
python run_satellites.py --night 150
python run_satellites.py --night 151
python run_satellites.py --night 152
python run_satellites.py --night 153
python run_satellites.py --night 154
python run_satellites.py --night 155
python run_satellites.py --night 156
python run_satellites.py --night 157
python run_satellites.py --night 158
python run_satellites.py --night 159
python run_satellites.py --night 160
python run_satellites.py --night 161
python run_satellites.py --night 162
python run_satellites.py --night 163
python run_satellites.py --night 164
python run_satellites.py --night 165
python run_satellites.py --night 166
python run_satellites.py --night 167
python run_satellites.py --night 168
python run_satellites.py --night 169
python run_satellites.py --night 170
python run_satellites.py --night 171
python run_satellites.py --night 172
python run_satellites.py --night 173
python run_satellites.py --night 174
python run_satellites.py --night 175
python run_satellites.py --night 176
python run_satellites.py --night 177
python run_satellites.py --night 178
python run_satellites.py --night 179
python run_satellites.py --night 180
python run_satellites.py --night 181
python run_satellites.py --night 191
python run_satellites.py --night 192
python run_satellites.py --night 193
python run_satellites.py --night 203
python run_satellites.py --night 210
python run_satellites.py --night 211
python run_satellites.py --night 212
python run_satellites.py --night 226
python run_satellites.py --night 232
python run_satellites.py --night 236
python run_satellites.py --night 292
python run_satellites.py --night 294
python run_satellites.py --night 296
python run_satellites.py --night 297
